### ISSUE TITLE
请问讯景6950xt除了仿冒6900xt还需要别的适配操作吗

### ISSUE THREAD

**Issue by yaohua-96** [RedamancyAY/Hackintosh-ASUS-ROG-STRIX-Z790-A-GAMING-WIFI-D4-i7-13700-6950XT#1]
你好，我在网上看见有人说讯景的 VBIOS 有问题，不知道 6000 系有没有解决。  
请问您组黑苹果时候讯景 6950xt 除了仿冒 6900xt 还需要别的适配操作吗

**Comment by RedamancyAY** [comment]
没有其他操作了，用了这么久，一直很稳定。
我之前的显卡也是讯景的5500xt，是免驱的，用了两年也没问题。

**Comment by yaohua-96** [comment]
:smile:感谢~
